"""add_visit_tracking_to_business

Revision ID: 56a2b033cead
Revises: c56c218b2500
Create Date: 2026-05-04 19:40:46.213412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a2b033cead'
down_revision: Union[str, Sequence[str], None] = 'c56c218b2500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('visit_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('businesses', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'last_seen_at')
    op.drop_column('businesses', 'visit_count')
    # ### end Alembic commands ###
