"""add_document_upload_fields

Revision ID: c56c218b2500
Revises: 204ad80fb567
Create Date: 2026-05-04 16:16:31.271526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56c218b2500'
down_revision: Union[str, Sequence[str], None] = '204ad80fb567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('business_documents', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_documents', 'is_available')
    op.drop_column('business_documents', 'original_filename')
    # ### end Alembic commands ###
