"""add_storage_mode_to_users_and_docs

Revision ID: eeb90b1c822e
Revises: 7e992c0f4a83
Create Date: 2026-05-04 13:35:24.846077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb90b1c822e'
down_revision: Union[str, Sequence[str], None] = '7e992c0f4a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_documents', sa.Column('storage_mode', sa.String(), nullable=True, server_default='LOCAL'))
    op.add_column('users', sa.Column('storage_mode', sa.String(), nullable=True, server_default='LOCAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_mode')
    op.drop_column('business_documents', 'storage_mode')
    # ### end Alembic commands ###
